# spring.application.name=project



server:
  port: 8080
  servlet:
    context-path: /

image-port: "http://localhost:8080"


spring:
  main:
    class: org.sale.project.ProjectApplication



  datasource:
    url: "jdbc:mysql://localhost:3306/quanao"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    password: root
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  session:
    store-type: jdbc
    timeout: 30m

    jdbc:
      initialize-schema: always

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 264565889451-li40qm8elg7569blr27vkuvb23qbmqe1.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: "{localhost:8080}/login/oauth2/code/google"
            scope:
              - email
              - profile
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v1/userinfo
            user-name-attribute: email



  devtools:
    restart:
      enabled: false
# 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
#email:
#  sendKey: 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

  mail:
    host: smtp.gmail.com
    port: 587
    username: syloftcloth@gmail.com # Lấy giá trị từ biến môi trường
    password: orszdsvtqxjgbfss # Lấy giá trị từ biến môi trường
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

payment:
  vnPay:
    url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    tmnCode: 5RIH2KL9
    secretKey: FPHVDV0OM6XV4K6A5646H7UX599AQV9F
    returnUrl: http://localhost:8080/pay/vn-pay-callback
    version: 2.1.0
    command: pay
    orderType: other

logging:
  level:
    org:
      springframework:
        security: debug